@Host = http://localhost:5200

### Get all Sound Files
GET {{Host}}/api/sound-files

### Upload new Sound File
POST {{Host}}/api/sound-files/test
Content-Type: multipart/form-data; boundary=----TestBoundary

------TestBoundary
Content-Disposition: form-data; name="file"; filename="test.mp3"
Content-Type: audio/mpeg

< Data/test.txt
------TestBoundary--

> {%
    client.global.set("soundFileId", response.body.id)
%}

### Get Sound File by ID
GET {{Host}}/api/sound-files/{{soundFileId}}

### Update Sound File Name
PATCH {{Host}}/api/sound-files/{{soundFileId}}/name/test2

### Get Sound File by ID again
GET {{Host}}/api/sound-files/{{soundFileId}}

### Get all Sound Templates
GET {{Host}}/api/sound-templates

### Create a new Sound Template
POST {{Host}}/api/sound-templates
Content-Type: application/json

{
  "name": "Test Sound Template",
  "description": "This is a test sound template",
  "rarity": "common",
  "minCooldown": 10,
  "maxCooldown": 20,
  "soundFileId": "{{soundFileId}}"
}

> {% 
    client.global.set("soundTemplateId", response.body.id)
%}

### Get Sound Template by ID
GET {{Host}}/api/sound-templates/{{soundTemplateId}}

### Get all Case Templates
GET {{Host}}/api/case-templates

### Create a new Case Template
POST {{Host}}/api/case-templates
Content-Type: application/json

{
  "name": "Test Case Template",
  "description": "This is a test case template",
  "rarity": "common"
}

> {%
    client.global.set("caseTemplateId", response.body.id)
%}

### Get Case Template by ID
GET {{Host}}/api/case-templates/{{caseTemplateId}}

### Get all Sound Templates in a Case Template
GET {{Host}}/api/case-templates/{{caseTemplateId}}/sound-templates

### Add Sound Template to Case Template
POST {{Host}}/api/case-templates/add-item-template
Content-Type: application/json

{
  "caseTemplateId": "{{caseTemplateId}}",
  "itemTemplateId": "{{soundTemplateId}}",
  "weight": 1
}

### Get all Sound Templates in a Case Template again
GET {{Host}}/api/case-templates/{{caseTemplateId}}/sound-templates



### Add User
POST {{Host}}/api/users
Content-Type: application/json

{
    "username": "tsolmonbat"
}

> {%
    client.global.set("userId", response.body.id)
%}

### Get User by ID
GET {{Host}}/api/users/{{userId}}

### Get User by Username
GET {{Host}}/api/users/username/tsolmonbat


### Get all Cases of User
GET {{Host}}/api/cases/{{userId}}

> {% 
    client.global.set("caseId", response.body.cases[0].id)
%}

### Get all Sounds of User
GET {{Host}}/api/sounds/{{userId}}

### Open Case by ID
POST {{Host}}/api/cases/{{caseId}}/open

### Get all Cases of User again
GET {{Host}}/api/cases/{{userId}}

### Get all Cases of User again
GET {{Host}}/api/sounds/{{userId}}

> {% 
    client.global.set("soundId", response.body.sounds[0].id)
%}

### Patch Sound by ID
PATCH {{Host}}/api/sounds/{{soundId}}/name/testSoundName


### Delete User by ID
DELETE {{Host}}/api/users/{{userId}}



###
DELETE {{Host}}/api/case-templates/{{caseTemplateId}}/item-template/{{soundTemplateId}}

### Get all Sound Templates in a Case Template again
GET {{Host}}/api/case-templates/{{caseTemplateId}}/sound-templates

### Delete Case Template by ID
DELETE {{Host}}/api/case-templates/{{caseTemplateId}}

### Delete Sound Template by ID
DELETE {{Host}}/api/sound-templates/{{soundTemplateId}}

### Delete Sound File by ID
DELETE {{Host}}/api/sound-files/{{soundFileId}}

### Get all Sound Files again
GET {{Host}}/api/sound-files