@Host = http://localhost:5200

### Add User
POST {{Host}}/api/users
Content-Type: application/json

{
  "username": "tsolmonbat"
}

> {% 
    client.global.set("userId", response.body.id) 
%}

### Get User by ID
GET {{Host}}/api/users/1

### Get User by Username
GET {{Host}}/api/users/username/tsolmonbat

> {%
    client.global.set("userId", response.body.id)
%}

###
GET {{Host}}/api/sound-files

###
POST {{Host}}/api/sound-files/test
Content-Type: multipart/form-data; boundary=----TestBoundary

------TestBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< Data/test.txt
------TestBoundary--

> {%
    client.global.set("soundFileId", response.body.id)
%}

####
GET {{Host}}/api/sound-files/{{soundFileId}}

###
PATCH {{Host}}/api/sound-files/{{soundFileId}}/name/test2

###
GET {{Host}}/api/sound-files/{{soundFileId}}

###
GET {{Host}}/api/sound-templates

###
POST {{Host}}/api/sound-templates
Content-Type: application/json

{
  "name": "Test Sound Template",
  "description": "This is a test sound template",
  "rarity": "common",
  "minCooldown": 10,
  "maxCooldown": 20,
  "soundFileId": "{{soundFileId}}"
}

> {% 
    client.global.set("soundTemplateId", response.body.id)
%}

###
GET {{Host}}/api/sound-templates/{{soundTemplateId}}

###
DELETE {{Host}}/api/sound-templates/{{soundTemplateId}}

###
DELETE {{Host}}/api/sound-files/{{soundFileId}}

###
GET {{Host}}/api/sound-files