@Host = http://localhost:5200

### Add User
POST {{Host}}/api/users
Content-Type: application/json

{
  "username": "tsolmonbat"
}

> {% 
    client.global.set("userId", response.body.id) 
%}

### Get User by ID
GET {{Host}}/api/users/{{userId}}

### Get User by Username
GET {{Host}}/api/users/username/tsolmonbat

> {%
    client.global.set("userId", response.body.id)
%}

###
GET {{Host}}/api/soundFiles

###
POST {{Host}}/api/soundFiles/test
Content-Type: multipart/form-data; boundary=----TestBoundary

------TestBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

< Data/test.txt
------TestBoundary--

> {%
    client.global.set("soundFileId", response.body.id)
%}

####
GET {{Host}}/api/soundFiles/{{soundFileId}}